<template>
    <div>
        <Slider 
          class="default-center-left-center-mt-0px-p-0px"
          :slidesPerView="1" 
          instanceId="slider" 
          syncWith="cards"
          :enableDrag="true"
          :enableTouch="true"
          :enablePauseButton="true"
          :enableDots="true"
          :enableArrows="true"
          :enableProgressBar="false"
          :enableCircleProgress="true"
          :enableProgressBarInPicture="true"
          :minSlides="4"
          :maxSlides="7"
          :activeSlideOn="5"
        />
      <Slider 
          class="card-center-center-mt-10px-p-10px-0"
          instanceId="cards" 
          syncWith="slider"
          :enableDrag="true"
          :enableTouch="true"
          :enableDots="false"
          :enableArrows="false"
          :enableProgressBar="false"
          :enableCircleProgress="false"
          :enablePauseButton="false"
          :enableProgressBarInPicture="true"
          :slidesPerView="4" 
          :minSlides="0"
          :maxSlides="10"
          :activeSlideOn="5"
        />
    </div>
</template>